export { default as PermissionsTab } from './PermissionsTab';
export { default as AlertsTab } from './AlertsTab';
export { default as ActivityTab } from './ActivityTab';
export { default as SystemTab } from './SystemTab';
export { default as ReportsTab } from './ReportsTab';
export { default as IslandsTab } from './IslandsTab';
export { default as ZonesTab } from './ZonesTab';
export { default as FAQTab } from './FAQTab';
export { default as ContentTab } from './ContentTab'; 