export const colors = {
    primary: "#4A90E2",
    primaryLight: "#E5F0FF",
    primaryDark: "#2E6AB8",
    secondary: "#5AC8C8",
    secondaryLight: "#E5F7F7",
    success: "#34C759",
    successLight: "#E8F8EA",
    warning: "#FF9500",
    warningLight: "#FFF4E5",
    danger: "#FF3B30",
    dangerLight: "#FFEBEA",
    error: "#FF3B30",
    errorLight: "#FFEBEA",
    info: "#007AFF",
    infoLight: "#E5F2FF",
    purple: "#8B5CF6",
    purpleLight: "#EDE9FE",
    text: "#1C1C1E",
    textSecondary: "#8E8E93",
    textTertiary: "#C7C7CC",
    background: "#FFFFFF",
    backgroundSecondary: "#F2F2F7",
    backgroundTertiary: "#F9F9FB",
    border: "#E5E5EA",
    borderLight: "#F2F2F7",
    card: "#FFFFFF",
    cardSecondary: "#FAFAFA",
    shadow: "rgba(0, 0, 0, 0.05)",
    shadowMedium: "rgba(0, 0, 0, 0.1)",
    shadowStrong: "rgba(0, 0, 0, 0.15)",
    white: "#FFFFFF",
    black: "#000000",
    gray: "#6B7280",
    overlay: "rgba(0, 0, 0, 0.5)",
};

export default {
    light: {
        text: colors.text,
        background: colors.background,
        tint: colors.primary,
        tabIconDefault: colors.textSecondary,
        tabIconSelected: colors.primary,
    },
};