/**
 * Trip Fare Override Editor
 *
 * Allows admins to override route segment fares for a specific trip
 */

import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { colors } from '@/constants/adminColors';
import { useAlertContext } from '@/components/AlertProvider';
import { ArrowRight, AlertCircle } from 'lucide-react-native';
import type {
  RouteSegmentFare,
  TripFareOverride,
} from '@/types/multiStopRoute';
import TextInput from '@/components/admin/TextInput';
import Button from '@/components/admin/Button';
import { formatCurrency } from '@/utils/currencyUtils';

interface TripFareOverrideEditorProps {
  tripId: string;
  routeSegmentFares: RouteSegmentFare[];
  existingOverrides: TripFareOverride[];
  onSave: (overrides: TripFareOverride[]) => Promise<void>;
  onCancel: () => void;
}

interface OverrideData {
  fare: number;
  reason: string;
}

export default function TripFareOverrideEditor({
  tripId,
  routeSegmentFares,
  existingOverrides,
  onSave,
  onCancel,
}: TripFareOverrideEditorProps) {
  const { showError, showInfo } = useAlertContext();
  const [overrides, setOverrides] = useState<Map<string, OverrideData>>(
    new Map()
  );
  const [saving, setSaving] = useState(false);

  // Load existing overrides
  useEffect(() => {
    const initialOverrides = new Map<string, OverrideData>();

    existingOverrides.forEach(override => {
      const key = `${override.from_stop_id}-${override.to_stop_id}`;
      initialOverrides.set(key, {
        fare: override.override_fare_amount,
        reason: override.reason || '',
      });
    });

    setOverrides(initialOverrides);
  }, [existingOverrides]);

  const handleFareChange = (
    fromStopId: string,
    toStopId: string,
    defaultFare: number,
    value: string
  ) => {
    const key = `${fromStopId}-${toStopId}`;

    // Handle empty input
    if (value === '' || value === null || value === undefined) {
      const newOverrides = new Map(overrides);
      newOverrides.delete(key);
      setOverrides(newOverrides);
      return;
    }

    const newFare = parseFloat(value);

    // Validate number
    if (isNaN(newFare) || newFare < 0) {
      return; // Invalid input, don't update
    }

    // If fare matches default, remove override
    if (newFare === defaultFare) {
      const newOverrides = new Map(overrides);
      newOverrides.delete(key);
      setOverrides(newOverrides);
    } else {
      const newOverrides = new Map(overrides);
      newOverrides.set(key, {
        fare: newFare,
        reason: overrides.get(key)?.reason || '',
      });
      setOverrides(newOverrides);
    }
  };

  const handleReasonChange = (
    fromStopId: string,
    toStopId: string,
    value: string
  ) => {
    const key = `${fromStopId}-${toStopId}`;
    const currentOverride = overrides.get(key);

    if (currentOverride) {
      const newOverrides = new Map(overrides);
      newOverrides.set(key, {
        ...currentOverride,
        reason: value,
      });
      setOverrides(newOverrides);
    }
  };

  const handleSave = async () => {
    // Validate all overrides have reasons
    const overridesWithoutReasons: string[] = [];

    overrides.forEach((override, key) => {
      if (!override.reason.trim()) {
        overridesWithoutReasons.push(key);
      }
    });

    if (overridesWithoutReasons.length > 0) {
      showInfo(
        'Validation Error',
        'Please provide a reason for all fare overrides'
      );
      return;
    }

    setSaving(true);
    try {
      const overrideArray: TripFareOverride[] = Array.from(
        overrides.entries()
      ).map(([key, data]) => {
        const [fromStopId, toStopId] = key.split('-');
        return {
          id: '', // Will be generated by database
          trip_id: tripId,
          from_stop_id: fromStopId,
          to_stop_id: toStopId,
          override_fare_amount: data.fare,
          reason: data.reason,
          created_at: '',
          updated_at: '',
        };
      });

      await onSave(overrideArray);
    } catch (error) {
      showError('Error', 'Failed to save fare overrides');
    } finally {
      setSaving(false);
    }
  };

  const getOverrideStatus = (
    fromStopId: string,
    toStopId: string,
    defaultFare: number
  ) => {
    const key = `${fromStopId}-${toStopId}`;
    const override = overrides.get(key);

    if (!override) return null;

    const difference = override.fare - defaultFare;
    const percentChange = ((difference / defaultFare) * 100).toFixed(1);

    return {
      isOverridden: true,
      difference,
      percentChange,
      isIncrease: difference > 0,
    };
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      {/* Info subtitle */}
      <View style={styles.header}>
        <Text style={styles.subtitle}>
          Modify fares for this specific trip only. Changes will not affect
          other trips on this route.
        </Text>
      </View>

      {/* Info banner */}
      <View style={styles.infoBanner}>
        <AlertCircle size={16} color={colors.info} />
        <Text style={styles.infoBannerText}>
          {overrides.size === 0
            ? 'All segments using route default fares'
            : `${overrides.size} segment${overrides.size > 1 ? 's' : ''} overridden`}
        </Text>
      </View>

      {/* Segment list */}
      <View style={styles.segmentsList}>
        {routeSegmentFares.map(segment => {
          const overrideStatus = getOverrideStatus(
            segment.from_stop_id,
            segment.to_stop_id,
            segment.fare_amount
          );
          const key = `${segment.from_stop_id}-${segment.to_stop_id}`;
          const override = overrides.get(key);
          const displayFare = override?.fare || segment.fare_amount;

          return (
            <View
              key={segment.id}
              style={[
                styles.segmentCard,
                overrideStatus && styles.segmentCardOverridden,
              ]}
            >
              {/* Segment header */}
              <View style={styles.segmentHeader}>
                <View style={styles.segmentRoute}>
                  <Text style={styles.segmentFrom}>
                    {segment.from_island_name}
                  </Text>
                  <ArrowRight size={14} color={colors.textSecondary} />
                  <Text style={styles.segmentTo}>{segment.to_island_name}</Text>
                </View>

                {overrideStatus && (
                  <View
                    style={[
                      styles.changeBadge,
                      overrideStatus.isIncrease
                        ? styles.changeBadgeIncrease
                        : styles.changeBadgeDecrease,
                    ]}
                  >
                    <Text
                      style={[
                        styles.changeText,
                        overrideStatus.isIncrease
                          ? styles.changeTextIncrease
                          : styles.changeTextDecrease,
                      ]}
                    >
                      {overrideStatus.isIncrease ? '+' : ''}
                      {overrideStatus.percentChange}%
                    </Text>
                  </View>
                )}
              </View>

              {/* Fare inputs */}
              <View style={styles.fareInputs}>
                <View style={styles.defaultFareContainer}>
                  <Text style={styles.defaultFareLabel}>Default Fare</Text>
                  <Text style={styles.defaultFareAmount}>
                    {formatCurrency(segment.fare_amount, 'MVR')}
                  </Text>
                </View>

                <View>
                  <TextInput
                    label='Override Fare (MVR)'
                    value={displayFare.toString()}
                    onChangeText={value => {
                      handleFareChange(
                        segment.from_stop_id,
                        segment.to_stop_id,
                        segment.fare_amount,
                        value
                      );
                    }}
                    keyboardType='decimal-pad'
                    placeholder='Enter custom fare amount'
                    editable={true}
                  />
                  {override && (
                    <Text style={styles.fareHint}>
                      Modified from {formatCurrency(segment.fare_amount, 'MVR')}
                    </Text>
                  )}
                </View>
              </View>

              {/* Reason input (only if overridden) */}
              {override && (
                <View style={styles.reasonContainer}>
                  <TextInput
                    label='Reason for Override'
                    value={override.reason}
                    onChangeText={value =>
                      handleReasonChange(
                        segment.from_stop_id,
                        segment.to_stop_id,
                        value
                      )
                    }
                    placeholder='e.g., Weekend promotion, Peak hour pricing'
                    multiline
                    numberOfLines={2}
                    required
                  />
                </View>
              )}
            </View>
          );
        })}
      </View>

      {/* Action buttons */}
      <View style={styles.actionButtons}>
        <View style={styles.buttonRow}>
          <View style={styles.buttonHalf}>
            <Button
              title='Cancel'
              variant='outline'
              onPress={onCancel}
              disabled={saving}
            />
          </View>
          <View style={styles.buttonHalf}>
            <Button
              title={
                overrides.size === 0
                  ? 'No Changes'
                  : `Save ${overrides.size} Override${overrides.size !== 1 ? 's' : ''}`
              }
              variant='primary'
              onPress={handleSave}
              loading={saving}
              disabled={overrides.size === 0}
            />
          </View>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
  },
  header: {
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 18,
    textAlign: 'center',
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    backgroundColor: colors.infoLight,
    borderRadius: 12,
    marginBottom: 20,
  },
  infoBannerText: {
    flex: 1,
    fontSize: 13,
    color: colors.info,
    fontWeight: '600',
  },
  segmentsList: {
    gap: 12,
    marginBottom: 24,
  },
  segmentCard: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 4,
  },
  segmentCardOverridden: {
    borderColor: colors.warning,
    borderWidth: 2,
    backgroundColor: `${colors.warning}08`,
  },
  segmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  segmentRoute: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  segmentFrom: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  segmentTo: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  changeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  changeBadgeIncrease: {
    backgroundColor: colors.errorLight,
  },
  changeBadgeDecrease: {
    backgroundColor: colors.successLight,
  },
  changeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  changeTextIncrease: {
    color: colors.error,
  },
  changeTextDecrease: {
    color: colors.success,
  },
  fareInputs: {
    gap: 12,
    marginTop: 4,
  },
  defaultFareContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  defaultFareLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  defaultFareAmount: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  reasonContainer: {
    marginTop: 12,
  },
  fareHint: {
    fontSize: 11,
    color: colors.warning,
    fontStyle: 'italic',
    marginTop: 4,
    marginLeft: 4,
  },
  actionButtons: {
    marginTop: 24,
    marginBottom: 20,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  buttonHalf: {
    flex: 1,
  },
});
